<a href="https://colab.research.google.com/github/Joao-VictorF/HCIA-AI_Huawei_Preparation/blob/main/Lab_02_Exercises_Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercises

#### 1. Import NumPy as np

In [1]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [2]:
np.zeros(10)
# output: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [3]:
np.ones(10)
# output: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [5]:
np.ones(10) + 4

# output: array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create an array of the integers from 10 to 50

In [7]:
np.arange(10, 51)
# output: array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
#                27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
#                44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

In [8]:
np.arange(10, 51, 2)
# outout: array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
#                44, 46, 48, 50])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
np.random.randint(0, 8, (3, 3)) #start, end, (rows, cols)
# output: array([[0, 1, 2],
#               [3, 4, 5],
#               [6, 7, 8]])

array([[7, 6, 4],
       [7, 7, 5],
       [6, 6, 3]])

#### 8. Create a 3x3 identity matrix

In [12]:
np.eye(3)
# output: array([[1., 0., 0.],
#                [0., 1., 0.],
#                [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Use NumPy to generate a random number between 0 and 1<br><br>&emsp;NOTE: Your result's value should be different from the one shown below.

In [23]:
np.random.rand(1)
# output: array([0.23442116])

array([0.98225754])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution<br><br>&emsp;&ensp;NOTE: Your result's values should be different from the ones shown below.

In [27]:
np.random.normal(0, 1, 25)
# output: array([-0.61659542, -0.77532828,  0.36213786, -1.28636974,  0.33286861,
#                 0.06991562,  0.99519046, -1.12320101, -2.09591218, -0.99818646,
#                -0.86720284, -1.13239342, -0.17099943, -0.76632253, -1.005097  ,
#                -1.73123788, -1.28889203, -1.63121734, -0.32411105, -0.30448115,
#                -0.67660156, -1.1030128 , -1.19426878,  1.10254174,  1.30879357])

array([-0.0639446 ,  1.58395015, -0.77648571, -2.13001564, -0.16305365,
        0.99331124, -0.35914162,  0.56950181, -0.12278334,  0.67898225,
        0.67214401,  0.75849966,  1.08887403,  0.56919596, -0.09230404,
       -0.54048181, -0.3585639 ,  2.6092508 ,  0.41589298, -1.12585481,
        0.21202288, -0.12392652,  0.00309288, -1.00652081,  1.47037229])

#### 11. Create the following matrix:

In [30]:
np.arange(0.01, 1.01, 1/100)
# output: array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
#       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
#       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
#       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
#       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
#       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
#       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
#       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
#       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
#       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [31]:
np.linspace(0, 1, 20)
# output: array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
#       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
#       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
#       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Now, you will be given a starting matrix, and you will replicate the matrix outputs.

##<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE:</strong> Do not forget to run the cell below!

In [32]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code that reproduces the output shown below.<br>

In [55]:
mat[np.ix_([2,3,4], [1,2,3,4])]
# output: array([[12, 13, 14, 15],
#       [17, 18, 19, 20],
#       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code that reproduces the output shown below.

In [56]:
mat[3,4]

# output: 20

20

#### 15. Write code that reproduces the output shown below.

In [57]:
mat[np.ix_([0,1,2], [1])]
# array([[ 2],
#       [ 7],
#       [12]])

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that reproduces the output shown below.

In [58]:
mat[4]
# output: array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

#### 17. Write code that reproduces the output shown below.

In [61]:
mat[3:5]
# output: array([[16, 17, 18, 19, 20],
#       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 18. Get the sum of all the values in mat

In [63]:
mat.sum()
# output: 325

325

#### 19. Get the standard deviation of the values in mat

In [67]:
mat.std()
# output: 7.211102550927978

7.211102550927978

#### 20. Get the sum of all the columns in mat

In [68]:
mat.sum(axis=0)
# output: array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])