<a href="https://colab.research.google.com/github/Joao-VictorF/HCIA-AI_Huawei_Preparation/blob/main/Lab_02_Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**
* Support for large, multi-dimensional arrays
* Mathematical functions to operate on these arrays
* All the values are from the same type
* NumPy arrays use less memory than Python lists:
* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
---
## **Colab Shortcuts**
* **CTRL+Space**: Auto complete
* **CTRL+Shift+Space**: Documentation
* **CTRL+Enter**: Run current cell
* **Shift+Enter**: Run current cell and move focus to the next cell (adding one if none exists)
* **Alt+Enter**: Run current cell and insert a new cell below it.
---


## Creating Arrays

In [1]:
import numpy as np

In [2]:
array1 = np.array([2, 4, 1])
array1

array([2, 4, 1])

In [ ]:
type(array1) # n-dimensional array

numpy.ndarray

In [ ]:
type([2, 4, 1])

list

In [20]:
matrix = np.array([[1, 4, 2], [7, 4, 2]])
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [ ]:
matrix[1]

array([7, 4, 2])

In [ ]:
matrix[1][0]

7

In [ ]:
matrix[1, 0]

7

In [ ]:
array2 = np.arange(1, 10) # array range

array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
print(np.arange(1, 10, 2)) #arange(start, stop, step) 
print(np.arange(0, 10, 5)) #arange(start, stop, step) 

[1 3 5 7 9]
[0 5]


In [ ]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [ ]:
zeros1d = np.zeros(5)
zeros1d

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
arr1 = np.linspace(1, 10, 5)
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.linspace(1, 11, 7)

array([ 1.        ,  2.66666667,  4.33333333,  6.        ,  7.66666667,
        9.33333333, 11.        ])

In [ ]:
np.random.rand(5)

array([0.83133248, 0.32052929, 0.33245164, 0.97068504, 0.34096725])

In [ ]:
random_array = np.random.rand(2, 3)
random_array

array([[0.69150385, 0.81882571, 0.95696716],
       [0.87224186, 0.25474342, 0.88008245]])

In [ ]:
np.random.randn(4)

array([ 0.11555967,  1.57133001,  0.68153235, -0.30259484])

In [ ]:
np.random.randint(2, 50)

27

In [15]:
np.random.randint(2, 50, (4, 2))

array([[20, 25],
       [30, 21],
       [34, 44],
       [40, 46]])

In [18]:
arr1.shape

(5,)

In [ ]:
matrix.shape

(2, 3)

In [ ]:
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [23]:
matrix.reshape(2, 3) # tem que ter a mesma quantidade de elementos

array([[1, 4, 2],
       [7, 4, 2]])

## Operations

In [ ]:
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr1.max()

10.0

In [ ]:
arr1.argmax()

4

In [ ]:
arr1.mean()

5.5

In [ ]:
arr1 + 2

array([ 3.  ,  5.25,  7.5 ,  9.75, 12.  ])

In [ ]:
arr1 * 3

array([ 3.  ,  9.75, 16.5 , 23.25, 30.  ])

In [ ]:
arr1 = np.random.randint(2, 50, 5)

In [ ]:
arr2 = np.random.randint(5, 60, 5)

In [ ]:
arr1

array([45, 42, 24,  6, 28])

In [ ]:
arr2

array([52, 45, 44, 21, 14])

In [ ]:
arr1 * arr2

array([2340, 1890, 1056,  126,  392])

In [ ]:
arr1 ** 2

array([2025, 1764,  576,   36,  784])

In [ ]:
np.sqrt(arr1)

array([6.70820393, 6.4807407 , 4.89897949, 2.44948974, 5.29150262])

In [ ]:
np.sum(arr1)

145

In [ ]:
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [ ]:
matrix2 = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [5, 6, 7, 8]])
matrix2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [5, 6, 7, 8]])

In [ ]:
matrix.shape

(2, 3)

In [ ]:
matrix2.shape

(3, 4)

In [ ]:
result = np.matmul(matrix, matrix2)
result

array([[19, 26, 33, 40],
       [25, 38, 51, 64]])

In [ ]:
result.shape

(2, 4)

In [ ]:
arr2d = np.random.randint(1, 100, (4, 5))
arr2d

array([[ 3,  8, 65, 74, 38],
       [78, 39, 65,  9, 81],
       [ 3, 85, 52, 77, 17],
       [ 9, 44,  8, 50, 59]])

In [ ]:
arr2d.sum()

864

In [ ]:
arr2d.sum(axis=0)

array([ 93, 176, 190, 210, 195])

In [ ]:
arr2d.sum(axis=1)

array([188, 272, 234, 170])

## Slices

In [24]:
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
arr1[1:4]

array([3.25, 5.5 , 7.75])

In [26]:
arr1[1:4] = 20

In [27]:
arr1

array([ 1., 20., 20., 20., 10.])

In [28]:
arr1[1:4] = np.arange(2, 5)
arr1

array([ 1.,  2.,  3.,  4., 10.])

In [29]:
matrix = np.random.randint(1, 50, (4, 5))
matrix

array([[ 6, 24, 27, 18, 43],
       [32,  8, 10, 17, 29],
       [42, 26, 25, 21, 15],
       [28, 23, 38, 21, 11]])

In [30]:
matrix[:,2:]

array([[27, 18, 43],
       [10, 17, 29],
       [25, 21, 15],
       [38, 21, 11]])

In [31]:
matrix[1:3, 1:3]

array([[ 8, 10],
       [26, 25]])

## Conditional Selecting

In [32]:
arr1

array([ 1.,  2.,  3.,  4., 10.])

In [33]:
arr1[0]

1.0

In [34]:
arr1[1:4]

array([2., 3., 4.])

In [35]:
arr1[[True, False, False, True, False]]

array([1., 4.])

In [36]:
arr1 < 10

array([ True,  True,  True,  True, False])

In [37]:
arr1[arr1 < 10]

array([1., 2., 3., 4.])